# STEPS:
#   1. deploy codes
#   2. restart odoo service

# 1. deploy codes
- name: Transfer files to {{ sit2_info }}
  template:
    src: "{{local}}/trunk{{item}}"
    dest: "{{remote}}/{{batch}}{{item}}"
  with_items: "{{ files }}"
  # register: result


# 2. restart odoo service
- name: Restart odoo service {{ sit2_info }}
  systemd:
    name: odoo
    state: restarted
  # when: result.changed

- name: Save to mongodb
  local_action: command mongo vbroker --host 172.18.6.164 --port 27017 --eval "db.deploy_log.save({date_created:'{{ansible_date_time.date}}',
                                                                                              time_created:'{{ansible_date_time.time}}',
                                                                                              server:'{{sit2_info}}',
                                                                                              server_ip:'{{ansible_default_ipv4.address}}',
                                                                                              mode:'adhoc sit2 deployment',
                                                                                              files:'{{files|list|to_json}}',
                                                                                              success:'yes'
                                                                                             })"
  # when: result.changed